### ISSUE TITLE
Bug with yii2 advanced template

### ISSUE THREAD

**Issue by klevron** [iutbay/yii2-imagecache#2]
Received by email from "_by the way communications AG_" :

> I use your ImageCache for Yii2 extetion extension. It is very cool thank you fot that very much.
> 
> But i have little problem. I test it with basic yii2 and it works great but , if i it test with yii2 advanced template, it dont work L
> 
> The Folder thumbs is not created. Can you maby help me?
> 
> Thanky you very much
> 
> My config :

```
'imageCache' => [
    'class' => 'iutbay\yii2imagecache\ImageCache',
    'sourcePath' => '@app/web/images',
    'sourceUrl' => '@web/images',
    'thumbsPath' => '@app/web/thumbs',
    'thumbsUrl' => '@web/thumbs',
    'sizes' => [
        'thumb' => [150, 150],
        'medium' => [300, 300],
        'large' => [600, 600],
    ],
],
'urlManager' => [
    'class' => 'yii\web\UrlManager',
    'enablePrettyUrl' => true,
    'showScriptName' => true,
    'rules' => [
        'thumbs/<path:.*>' => 'pressroom/thumb',
    ],
],
```

> My controller :

```
public function actions()
{
    return [
        'thumb' => 'iutbay\yii2imagecache\ThumbAction',
    ];
}
```

> And view :

```
<?=Yii::$app->imageCache->thumb('/images/01.1051.103.png')?>
```

**Comment by ekawalec** [comment]
any solutions ??? i've got the same issue :(

'imageCache' => [
    'class' => 'iutbay\yii2imagecache\ImageCache',
    'sourcePath' => '@app/web/uploaded',
    'sourceUrl' => '@web/uploaded',
    'thumbsPath' => '@app/web/thumbs',
    'thumbsUrl' => '@web/thumbs',
    'sizes' => [
        'thumb' => [30, 30],
//        'medium' => [300, 300],
//        'large' => [600, 600],
    ],
],
'urlManager' => [
    'class' => 'yii\web\UrlManager',
    'enablePrettyUrl' => true,
    'showScriptName' => true,
    'rules' => [
        'thumbs/path:.*' => 'site/thumb',
    ],
],

controller:

public function actions()
{
    return [
        'thumb' => 'iutbay\yii2imagecache\ThumbAction',
    ];
}

error 404

**Comment by klevron** [comment]
Hello, I will try to fix this next week... But feel free to make a pull request :-)

**Comment by klevron** [comment]
Well, tested and it works.
